### PR TITLE
Use package randombytes

### PR DESCRIPTION
**Pull request by fanatid**
In addition to https://github.com/tristanls/k-bucket/pull/14
new:
```
$ ./node_modules/.bin/browserify index.js |wc -c
108184
```
old:
```
$ ./node_modules/.bin/browserify index.js |wc -c
591337
```

### CODE REVIEW

**Comment by feross** [comment]
LGTM

**Comment by fanatid** [comment]
@feross as I understand this package is part of [webtorrent](https://github.com/feross/webtorrent) ? I mean this code are weirdly used in browser?

**Comment by feross** [comment]
This package is not actually shipped in the browser version of WebTorrent
because bittorrent-dht does not work in the browser yet. But I think this
change is fine one. :)

**Comment by fanatid** [comment]
OOI why [bittorrent-dht](https://github.com/feross/bittorrent-dht) doesn't work in browser?

**Comment by feross** [comment]
It sends UDP packets, which does not work in the browser.

**Comment by fanatid** [comment]
oh, exactly, I forgot about this! Thank you @feross

**Pull request merged**
