### PR TITLE
There is nothing Buffer-specific used here, so simpler Uint8Array should also be accepted

### PR DESCRIPTION
**Pull request by nazar-pc**
In modern versions of Node.js (4+) `Buffer` extends `Uint8Array`, so this is not even a breaking change

### CODE REVIEW

**Comment by fanatid** [comment]
What is the purpose of this changes?
I think you are wrong about this this is not breaking change: you changed signature of function `distance`, projects who uses `k-bucket` can expect `Buffer` as input and use `Buffer` function which `Uint8Array` is not provide (swap/write/read/copy/etc).

**Comment by nazar-pc** [comment]
I'm working with this library in browser environment and it is very inconvenient to carry `Buffer` polyfill and convert data back and forth every time I need to interact with `k-bucket`, so it would be nice to avoid that and work with `Uint8Array` without any additional overhead.

`k-bucket` doesn't produce or modify any `Buffer` objects, it returns whatever was received in method call. Existing projects that use `Buffer` will continue working as before, but new projects will be able to avoid `Buffer` overhead if they wish.

**Comment by fanatid** [comment]
```js
const KBucket = require('k-bucket')
const { randomBytes } = require('crypto')

new KBucket({
  localNodeId: randomBytes(4),
  distance: (b1, b2) => Math.abs(b1.readUInt32BE(0) - b2.readUInt32BE(0))
})
```
still not breaking change?

**Comment by nazar-pc** [comment]
You've produced `Buffer` in `randomBytes()` and it will be carried without changes to `distance()` call, hence no problems with calling `readUint32BE()`.

New projects will need to be careful, but existing projects will not notice any difference.

If you think it is more appropriate to increase major version - I have no problems with that.

**Comment by tristanls** [comment]
How about making it pluggable, the way `Kbucket.distance` and `Kbucket.arbiter` ended up?

I'm thinking `Kbucket.isIdType(...)` and `Kbucket.idsEqual(...)`.

The default implementations would remain as `Buffer`, but then overriding `isIdType` and `idsEqual` would enable using `Uint8Array`, or anything else for that matter? Would you still need to carry around a polyfill or would code elimination take care of it?

This might require making `_determineNode` pluggable as well... but that can be probably deferred until someone wants to use ids that break the buffer assumption?

**Comment by nazar-pc** [comment]
Proposed arrays comparison works perfectly with `Buffer` too or even mix of `Buffer`/`Uint8Array`. There is really no point to have something specific for `Buffer` unless you want to support even more types.

> Would you still need to carry around a polyfill or would code elimination take care of it?

In my case browserify will include polyfill and configuring it without polyfill through nested dependencies would be a pain.

**Comment by tristanls** [comment]
So, switching to `Uint8Array` would change the default implementation and reduce dependencies.

Exposing `Kbucket.isIdType(...)` and `Kbucket.idsEqual(...)` would enable Node.js-land to use Buffers as/if desired.

**Comment by nazar-pc** [comment]
`Buffer` extends `Uint8Array` in Node.js, what is the purpose of exposing mentioned methods?

**Comment by tristanls** [comment]
`add` benchmark before:
```
> node benchmarks/add.js

Seed: 701196b6b12ef999079072360ed57ea3cd984546ea8fe7487175e7f79447b251
KBucket.add: 468.854ms
Memory:  { rss: 33804288,
  heapTotal: 11354112,
  heapUsed: 6666504,
  external: 157108 }

> node benchmarks/add.js

Seed: c7023d1286345028c3338b4ef5acc7eba68b666a2d111e1610a3e212bb90beea
KBucket.add: 453.693ms
Memory:  { rss: 34811904,
  heapTotal: 11354112,
  heapUsed: 6841464,
  external: 168724 }

> node benchmarks/add.js

Seed: e07ea598e8664df4fbdb401b684069155cf59c24526ca207bab33b401efe1927
KBucket.add: 467.869ms
Memory:  { rss: 35942400,
  heapTotal: 11354112,
  heapUsed: 6855160,
  external: 169940 }

> k-bucket@3.3.1 benchmark:add /Users/tristan/code/github/tristanls/k-bucket
> node benchmarks/add.js

Seed: 2335c48524bbbd308361ccc34abb481d1de747deed199e62f0af15f821b902e2
KBucket.add: 469.807ms
Memory:  { rss: 34811904,
  heapTotal: 15548416,
  heapUsed: 5945104,
  external: 110580 }

> node benchmarks/add.js

Seed: dea4988ed4e28bf1a78a064ccbd38192ae912a658de31a5c075c400f36a25dfe
KBucket.add: 476.680ms
Memory:  { rss: 33931264,
  heapTotal: 11354112,
  heapUsed: 6688392,
  external: 159380 }

```
`add` benchmark after:
```

> node benchmarks/add.js

Seed: 91b5734b93de674f33f62287ba5b436cd6c6f2c1f56e659039dfc7060161bf2d
KBucket.add: 313.885ms
Memory:  { rss: 36315136,
  heapTotal: 11354112,
  heapUsed: 7357440,
  external: 204116 }

> node benchmarks/add.js

Seed: 9aca6e3dd8d439faa64db9e7e8a8ced792a0712180f007557eeaf0ad5034634f
KBucket.add: 304.601ms
Memory:  { rss: 35401728,
  heapTotal: 11354112,
  heapUsed: 7336824,
  external: 202356 }

> node benchmarks/add.js

Seed: e5fba02977370faa4a2ec07a0f24e81c1bff68d2ae8b853816556afa9dde079e
KBucket.add: 310.042ms
Memory:  { rss: 34332672,
  heapTotal: 15548416,
  heapUsed: 5543424,
  external: 84148 }

> node benchmarks/add.js

Seed: eacea7be85892165cf051ead7652db85087652b931d02035e2918d23bd811b52
KBucket.add: 287.990ms
Memory:  { rss: 32137216,
  heapTotal: 11354112,
  heapUsed: 7367800,
  external: 204372 }

> node benchmarks/add.js

Seed: a777f548244c50ad97c4ad0131c42a9c61b42fb7fbc51e0e8d6527835eb505de
KBucket.add: 283.627ms
Memory:  { rss: 34000896,
  heapTotal: 11354112,
  heapUsed: 7360352,
  external: 203444 }

> node benchmarks/add.js

Seed: 14d9063fdc352b3935846280b351c835235a6173fa8119abec0debc5ec894484
KBucket.add: 284.773ms
Memory:  { rss: 33406976,
  heapTotal: 11354112,
  heapUsed: 7163032,
  external: 190996 }

> node benchmarks/add.js

Seed: 056bcc0a21c3a3d315df8281c250b191dba790e1081723e2e578904334ba9203
KBucket.add: 297.322ms
Memory:  { rss: 33910784,
  heapTotal: 15548416,
  heapUsed: 5529288,
  external: 82708 }

> node benchmarks/add.js

Seed: 3ca0e07c95bf6d6c5203a70b1a7f4d480cd3fe45c89acf2e4fc824a5c00ec97c
KBucket.add: 316.356ms
Memory:  { rss: 33574912,
  heapTotal: 11354112,
  heapUsed: 7359624,
  external: 204084 }

```

**Comment by tristanls** [comment]
Distance benchmark seems same-ish.

**Comment by tristanls** [comment]
Released [v4.0.0](https://github.com/tristanls/k-bucket/releases/tag/v4.0.0)

**Pull request merged**
