### PR TITLE
Remove recursion in KBucket

### PR DESCRIPTION
**Pull request by fanatid**
This PR demonstrate idea from #34 
if you ok with this, I'll fix tests

### CODE REVIEW

**Comment by tristanls** [comment]
Ok, I see what the nature of the change is now, thank you for showing it via code.

I can see a way to benchmark the speed. I'm still uncertain how to profile lower memory. 

My assumption, based on comments in #34, is that this pull request will improve speed, memory consumption, or both, without making any worse. It's fine to me if the speed and/or memory criteria are met.

**Comment by fanatid** [comment]
Updated. Tests are fixed now.
@tristanls is benchmark required for merge this PR? If so, I'll try write something (but I think, numbers can be almost the same influenced by jitter).

**Comment by tristanls** [comment]
@fanatid, welcome back :)

Without some sort of way to measure the difference, why is this an improvement? If it's not an improvement, why do anything?

**Comment by fanatid** [comment]
Benchmark for `KBuket.add`:
```bash
(old)
$ SEED=944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001 node add.js 
Seed: 944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001
KBucket.add: 930.976ms
Memory:  { rss: 37056512, heapTotal: 15724544, heapUsed: 5543600 }
$ SEED=944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001 node add.js 
Seed: 944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001
KBucket.add: 918.060ms
Memory:  { rss: 36798464, heapTotal: 15724544, heapUsed: 7983504 }
$ SEED=944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001 node add.js 
Seed: 944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001
KBucket.add: 929.083ms
Memory:  { rss: 36950016, heapTotal: 15724544, heapUsed: 8001008 }

(new)
$ SEED=944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001 node add.js 
Seed: 944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001
KBucket.add: 919.014ms
Memory:  { rss: 37085184, heapTotal: 15724544, heapUsed: 6294584 }
$ SEED=944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001 node add.js 
Seed: 944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001
KBucket.add: 921.948ms
Memory:  { rss: 36995072, heapTotal: 15724544, heapUsed: 6302752 }
$ SEED=944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001 node add.js 
Seed: 944f41e2735008807c0a023244042dc6bba49b971cb983d252c61f348a959001
KBucket.add: 862.595ms
Memory:  { rss: 37371904, heapTotal: 15724544, heapUsed: 6308344 }
```

**Comment by tristanls** [comment]
Agreed, I see similar behavior on my machine.

```
$ node -v
v6.3.1

[k-bucket (feature/non-recursive %=)]$ node _tmp/_add.js 
Seed: a9b220adad92e1ecdd014c7582959942363909e1929b4a580292c01538dd072b
KBucket.add: 903.401ms
Memory:  { rss: 34217984, heapTotal: 15724544, heapUsed: 6305320 }
[k-bucket (feature/non-recursive %=)]$ node _tmp/_add.js 
Seed: 336f4b6e8ca073ee803ff753ad00a024cf1218c905c92b7c2d0e6f4a979464ed
KBucket.add: 871.725ms
Memory:  { rss: 34127872, heapTotal: 15724544, heapUsed: 6301776 }
[k-bucket (feature/non-recursive %=)]$ node _tmp/_add.js 
Seed: 5cfea93f7323fa32169a9b40f3c0cc839220514c2d5fa7e10c46f36182ecaf5d
KBucket.add: 856.090ms
Memory:  { rss: 35250176, heapTotal: 15724544, heapUsed: 5851992 }
[k-bucket (feature/non-recursive %=)]$ node _tmp/_add.js 
Seed: 3fdcf1e2971facad2423b070026c8038858447d714f09cad4d90d5aa433c85d5
KBucket.add: 860.850ms
Memory:  { rss: 34304000, heapTotal: 15724544, heapUsed: 5868760 }
[k-bucket (feature/non-recursive %=)]$ node _tmp/_add.js 
Seed: c40f5faddd703631d3be6a8e97e69e0ace46cf8261f47d3d5a02efefd03bb874
KBucket.add: 860.164ms
Memory:  { rss: 35237888, heapTotal: 15724544, heapUsed: 5870328 }
[k-bucket (feature/non-recursive %=)]$ node _tmp/_add.js 
Seed: eab42f99fbfbaaf01040a25fb0c4d63b4066775e6e49c23c5858da3c2a77f34a
KBucket.add: 860.007ms
Memory:  { rss: 35631104, heapTotal: 15724544, heapUsed: 6296016 }
[k-bucket (feature/non-recursive %=)]$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[k-bucket (master %=)]$ node _tmp/_add.js 
Seed: d214701fd5f1481ff9b6d9668cc2c32aaeebd01b0b0f4c47e8bf1ab081ea944e
KBucket.add: 871.814ms
Memory:  { rss: 35389440, heapTotal: 15724544, heapUsed: 7999312 }
[k-bucket (master %=)]$ node _tmp/_add.js 
Seed: 42f49bace0a9d41960f66feb98b4f1105fe93dc15f055a21cb2ed7651056fd09
KBucket.add: 862.559ms
Memory:  { rss: 36229120, heapTotal: 15724544, heapUsed: 8026056 }
[k-bucket (master %=)]$ node _tmp/_add.js 
Seed: 41de7d30beb4cbf36aacba01aa885929951e5ba1e1af76ab7e12a2e7a35ee731
KBucket.add: 879.634ms
Memory:  { rss: 35143680, heapTotal: 15724544, heapUsed: 7994664 }
[k-bucket (master %=)]$ node _tmp/_add.js 
Seed: c1b556f3bae66745f18d53ba6e4f3f8bc0a8f782e4b5e707fc021613476c24d0
KBucket.add: 877.387ms
Memory:  { rss: 34439168, heapTotal: 15724544, heapUsed: 7981200 }
[k-bucket (master %=)]$ node _tmp/_add.js 
Seed: a48674476ebfcbbfb06b52ac5c9701cf59d0b10bb36e6d7bb0cccd8fa82833d4
KBucket.add: 884.902ms
Memory:  { rss: 35414016, heapTotal: 15724544, heapUsed: 8007912 }
```

**Comment by fanatid** [comment]
Almost same time, but memory consumption is better. Are you going to merge this PR? :)

**Comment by fanatid** [comment]
@tristanls can you wait #36 for new release?

**Comment by tristanls** [comment]
lol... oops

**Comment by fanatid** [comment]
yep, I checked history after message.. never mind, all fine :)

**Comment by feross** [comment]
It appears that this PR changed behavior in a way that affected bittorrent-dht: https://github.com/tristanls/k-bucket/issues/38

**Pull request merged**
