### PR TITLE
Improve .distance

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by tristanls** [comment]
Yup, before (per `1e7` invocations):
`~3031421920`
after:
`~0101792535`

**Comment by tristanls** [comment]
But, I get test failures...
```
✖ distance between 00000000 and 0000000000000000 is 0000000011111111

AssertionError: 256 == 255

✖ distance between 0000000100100100 and 0100000000100100 is 0100000100000000

AssertionError: 16640 == 1040
```

**Comment by fanatid** [comment]
fixed

**Comment by tristanls** [comment]
```
[tristan: k-bucket ((3577e75...))]$ npm tst

> k-bucket@2.0.0 test /Volumes/github/tristanls/k-bucket
> node scripts/test.js

...

distance
✔ distance between 00000000 and 00000000 is 00000000
✔ distance between 00000000 and 00000001 is 00000001
✔ distance between 00000010 and 00000001 is 00000011
✔ distance between 00000000 and 0000000000000000 is 0000000011111111
✖ distance between 0000000100100100 and 0100000000100100 is 0100000100000000

AssertionError: 16640 == 1040
```

**Comment by fanatid** [comment]
sorry, forgot about tests.. your test was wrong, because old version of `distance` has a bug:
```js
(firstId[i] ^ secondId[i]).toString(16)
```
can return one symbol, but should 2

**Comment by tristanls** [comment]
Thank you! I'll cherry-pick this into the 1.0 and 2.0 branches as well.

**Pull request merged**
