### PR TITLE
Added additional base64 string support.

### PR DESCRIPTION
**Pull request by nathanph**
The public functions: distance, add, closest, get, and remove now
support passing in node ids of type base64 in addition to Buffer.

### CODE REVIEW

**Comment by nathanph** [comment]
I wanted this feature for a project I'm working on so I added them to the package. I'm not sure if it's worthwhile to add to your package, but I figured I'd let you make that decision.

**Comment by tristanls** [comment]
Hey, did you change your mind? 

Sorry for not responding. Since this was more a feature than a bug, I was giving myself more time to get around it.

**Comment by nathanph** [comment]
No, take your time. I thought I had found a bug while I was using it so I took it down, turns out the issue was in external code. I can probably write some tests for you if you'd like.

**Comment by feross** [comment]
@nathanph Any reason this feature has to go in the library? Why can't you call `new Buffer(str, 'base64')` in your own code?

**Comment by nathanph** [comment]
It definitely doesn't _have_ to go into the library. My thought process was that if could pass in a base64 string in the constructor for the ```localNodeId```, then I should also be able to pass in base64 strings for ```contact.id```s. Before I re-read the documentation I had naïvely assumed that was the case. I think universally allowing only Buffers or universally allowing both Buffers and base64 is clearer than allowing both, but only in some methods/parameters. 

This is really just my opinion on code consistency, but I wouldn't be offended if this doesn't make its way into the library. The fact that no one before me has mentioned this suggests it might not be that big an issue. Who's to say really?

**Comment by tristanls** [comment]
Thanks for elaborating further. I think the principle of least surprise makes sense, I didn't notice that about the module API before. If we're going to make it consistent, I'd rather make it consistent the "other" way, that is make `localNodeId` only allow a Buffer. We'd bump to 0.5.0 of course.

My concern is if that would generate bunch of work for @feross ?

**Comment by nathanph** [comment]
I tend to agree that just having Buffers is more appropriate. 

Gracefully deprecating is always a pain. Rather than immediately removing the base64 string feature I would suggest adding a comment in the README.md and code that the String functionality has been deprecated, then remove the String functionality in a few months so that anyone who used strings for ```localNodeId``` has an opportunity to correct their code before you actually remove the option from the package altogether.

Alternatively you could remove the string option from the README.md, add a comment in the code that the feature is deprecated, but never actually remove the functionality from the package. This way you won't have to worry about breaking anyone's code.

In an ideal world people are using their package mangers properly and won't have to worry about feature breaking code in any condition.

**Comment by feross** [comment]
+1 to making it consistent by either allowing Buffer only, or Buffer and base64 strings for all methods.

Either way, this won't create work for me. `bittorrent-dht` always passes a Buffer to `k-bucket`.

**Pull request closed without merging**
